# sales='tameshwar'
# print(sales[1:9:2])
# print(sales[::1])
# print(sales[::-1])

# val='nitin'
# if val[::1]==val[::-1]:
#     print('palindrome')
# else:
#     print('not palindrome')

# utube
# name='shavali'
# name.capitalize()
# print(name)

# name=input('Enter Your Name :')
# print(f'Good Morning',{name})

# l1=['harry','shavali',12,41,]
# print(l1)

#sort by asc
# l1=[2,3,5,6,84,22]
# l1.sort()
# print(l1)

# append (To add value in last)
# l1=[2,3,5,6,84,22]
# l1.append(18)
# print(l1)

# Reverse Order
# l1=[2,33,56,48,75,6]
# l1.reverse()
# print(l1)

#pop (delete the number)
# l1=[2,33,56,48,75,6]
# l1.pop(5)
# print(l1)

# remove() it removes the values
# l1=[2,33,56,48,75,6]
# l1.remove(56)
# print(l1)

# a=(1,7,2)
# a.index(1)
# print(a)